### ISSUE TITLE
Using Tag Helper Does Not Appear To Be Using Placeholder Text

### ISSUE THREAD

**Issue by AlexSafatli** [NARKOZ/holder_rails#12]
Here's an example. On my Rails application, I tried placing the following into one of my views.

    = holder_tag '210x200', 'Lorem Ipsum'

But I only received the following render on my page.

![](https://photos-6.dropbox.com/t/2/AADKTI2wbLpIqCvsVwvKecjUyYFkK_hrzDWN1wuqOf6Z1g/12/146710/png/32x32/1/1445522400/0/2/Screenshot%202015-10-22%2009.13.49.png/CJb6CCABIAIgAyAFIAcoAigH/uPnsXfeDezy5DaxML1s5A2H7XhoHAOgxoQBtBS3zkg0?size=1280x960&size_mode=2)

Any idea what's going wrong? If I try using the syntax as described in the `Holder.js` readme, i.e.

    data-src=("holder.js/210x200?auto=yes&size=30&text=Lorem Ipsum")

I will get, correctly, the following.

![](https://photos-4.dropbox.com/t/2/AAA3lOQCjTunLZeTVZwLwZWZa6e8KKwM6nKL4QJ4Sx83Vg/12/146710/png/32x32/1/1445522400/0/2/Screenshot%202015-10-22%2009.15.43.png/CJb6CCABIAIgAyAFIAcoAigH/04izPs0IzWDLoj-PdVkho2qzTQa5M2_RBBXSLcJoBr8?size=1280x960&size_mode=2)

**Comment by NARKOZ** [comment]
Version 2.9.0 was released with a fix.
